apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ps-eks-44 
  region: us-west-1
  version: "1.23"
availabilityZones: [us-west-1a, us-west-1b]
managedNodeGroups:
- name: nodegroup
  instanceType: m5.2xlarge
  volumeSize: 100
  minSize: 2
  maxSize: 4
  desiredCapacity: 2
  ssh:
    allow: true
    publicKeyName: ps-west-1-831675306254
 # privateNetworking: true
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
    - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy    
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
    - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    - arn:aws:iam::aws:policy/AmazonS3FullAccess  #you can create policy specfic for bucket created
    withAddonPolicies:
      autoScaler: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"] 
